server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CoolRonin/aispringcloud
          searchPaths: config
          username: CoolRonin
          password: hjl2578417030
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
